//! Plain-text chunker WASM plugin — splits text on blank lines.
//!
//! Compile: `cargo build --target wasm32-wasip2 --example plain-text-chunker -p virage-engine-sdk`

wit_bindgen::generate!({
    world: "chunker",
    path: "wit",
});

// Types are in root scope (generated by wit_bindgen::generate! for this world)
struct PlainTextChunker;

impl Guest for PlainTextChunker {
    fn init(_config_json: String) -> Result<(), String> {
        Ok(())
    }

    fn patterns() -> Vec<String> {
        vec!["**/*.txt".to_string(), "**/*.md".to_string()]
    }

    fn parse(_info: FileInfo, bytes: Vec<u8>) -> Result<String, String> {
        String::from_utf8(bytes).map_err(|e| e.to_string())
    }

    fn chunk(doc_json: String, info: FileInfo, commit_hash: String) -> Result<Vec<Chunk>, String> {
        let chunks = doc_json
            .split("\n\n")
            .filter(|s| !s.trim().is_empty())
            .enumerate()
            .map(|(i, text)| {
                let trimmed = text.trim();
                let dense = format!("[{}] {}", info.path, trimmed);
                Chunk {
                    dense_text: dense.clone(),
                    sparse_text: trimmed.to_string(),
                    dense_text_hash: format!("{:08x}", simple_hash(&dense)),
                    source_file: info.path.clone(),
                    commit_hash: commit_hash.clone(),
                    metadata_json: format!("{{\"paragraph\":{i}}}"),
                }
            })
            .collect();
        Ok(chunks)
    }
}

fn simple_hash(s: &str) -> u32 {
    s.bytes().fold(0x811c9dc5u32, |h, b| {
        h.wrapping_mul(0x01000193).wrapping_add(b as u32)
    })
}

export!(PlainTextChunker);
