//! Sandbox probe — attempts to read /etc/passwd during `parse`.
//!
//! Used in host tests to verify that the WASI sandbox correctly denies
//! filesystem access when no preopened directories are configured.
//!
//! Compile: `cargo build --target wasm32-wasip2 --example sandbox-probe -p virage-engine-sdk`

wit_bindgen::generate!({
    world: "chunker",
    path: "wit",
});

// Types are in root scope (generated by wit_bindgen::generate! for this world)
struct SandboxProbe;

impl Guest for SandboxProbe {
    fn init(_config_json: String) -> Result<(), String> {
        Ok(())
    }

    fn patterns() -> Vec<String> {
        vec!["**/*".to_string()]
    }

    fn parse(_info: FileInfo, _bytes: Vec<u8>) -> Result<String, String> {
        // Attempt FS access — WASI sandbox with no preopened dirs must deny this.
        match std::fs::read("/etc/passwd") {
            Ok(data) => {
                // If we get here the sandbox failed — return a marker so the test
                // knows to fail, rather than panicking inside the component.
                Ok(format!("FS_ACCESS_GRANTED:{}", data.len()))
            }
            Err(e) => Ok(format!("FS_ACCESS_DENIED:{e}")),
        }
    }

    fn chunk(
        doc_json: String,
        _info: FileInfo,
        _commit_hash: String,
    ) -> Result<Vec<Chunk>, String> {
        // doc_json carries the result from parse() — forward it as a single chunk
        // so the host can inspect it.
        Ok(vec![Chunk {
            dense_text: doc_json.clone(),
            sparse_text: doc_json,
            dense_text_hash: "00000000".to_string(),
            source_file: String::new(),
            commit_hash: String::new(),
            metadata_json: "{}".to_string(),
        }])
    }
}

export!(SandboxProbe);
