import type { VendorConfig } from "../types/vendor.js";

export const CLAUDE_VENDOR_CONFIG: VendorConfig = {
  vendor: "claude",
  supportedEvents: [
    "session_start",
    "session_end",
    "setup",
    "instructions_loaded",
    "user_prompt_submit",
    "user_prompt_expansion",
    "message_display",
    "pre_tool_use",
    "post_tool_use",
    "post_tool_use_failure",
    "post_tool_batch",
    "permission_request",
    "permission_denied",
    "subagent_start",
    "subagent_stop",
    "task_created",
    "task_completed",
    "agent_stop",
    "stop_failure",
    "pre_compact",
    "post_compact",
    "notification",
    "config_change",
    "cwd_changed",
    "file_changed",
    "worktree_create",
    "worktree_remove",
    "elicitation",
    "elicitation_result",
    "teammate_idle",
  ],
  hookTypes: ["command", "http", "mcp_tool", "prompt", "agent"],
  configLocations: [
    "~/.claude/settings.json",
    ".claude/settings.json",
    ".claude/settings.local.json",
  ],
  eventNameMap: {
    session_start: "SessionStart",
    session_end: "SessionEnd",
    setup: "Setup",
    instructions_loaded: "InstructionsLoaded",
    user_prompt_submit: "UserPromptSubmit",
    user_prompt_expansion: "UserPromptExpansion",
    message_display: "MessageDisplay",
    pre_tool_use: "PreToolUse",
    post_tool_use: "PostToolUse",
    post_tool_use_failure: "PostToolUseFailure",
    post_tool_batch: "PostToolBatch",
    permission_request: "PermissionRequest",
    permission_denied: "PermissionDenied",
    subagent_start: "SubagentStart",
    subagent_stop: "SubagentStop",
    task_created: "TaskCreated",
    task_completed: "TaskCompleted",
    agent_stop: "Stop",
    stop_failure: "StopFailure",
    error_occurred: null,
    pre_invocation: null,
    post_invocation: null,
    pre_compact: "PreCompact",
    post_compact: "PostCompact",
    notification: "Notification",
    config_change: "ConfigChange",
    cwd_changed: "CwdChanged",
    file_changed: "FileChanged",
    worktree_create: "WorktreeCreate",
    worktree_remove: "WorktreeRemove",
    elicitation: "Elicitation",
    elicitation_result: "ElicitationResult",
    teammate_idle: "TeammateIdle",
  },
};

export const COPILOT_VENDOR_CONFIG: VendorConfig = {
  vendor: "copilot",
  supportedEvents: [
    "session_start",
    "session_end",
    "user_prompt_submit",
    "pre_tool_use",
    "post_tool_use",
    "post_tool_use_failure",
    "permission_request",
    "subagent_start",
    "subagent_stop",
    "agent_stop",
    "error_occurred",
    "pre_compact",
  ],
  hookTypes: ["command", "http", "prompt"],
  configLocations: [
    ".github/hooks/*.json",
    "~/.copilot/hooks/",
    ".github/copilot/settings.json",
  ],
  eventNameMap: {
    session_start: ["sessionStart", "SessionStart"],
    session_end: ["sessionEnd", "SessionEnd"],
    user_prompt_submit: ["userPromptSubmitted", "UserPromptSubmit"],
    pre_tool_use: ["preToolUse", "PreToolUse"],
    post_tool_use: ["postToolUse", "PostToolUse"],
    post_tool_use_failure: ["postToolUseFailure", "PostToolUseFailure"],
    permission_request: "permissionRequest",
    subagent_start: "subagentStart",
    subagent_stop: ["subagentStop", "SubagentStop"],
    agent_stop: ["agentStop", "Stop"],
    error_occurred: ["errorOccurred", "ErrorOccurred"],
    pre_compact: ["preCompact", "PreCompact"],
  },
};

export const CODEX_VENDOR_CONFIG: VendorConfig = {
  vendor: "codex",
  supportedEvents: [
    "session_start",
    "user_prompt_submit",
    "pre_tool_use",
    "post_tool_use",
    "permission_request",
    "subagent_start",
    "subagent_stop",
    "agent_stop",
    "pre_compact",
    "post_compact",
  ],
  hookTypes: ["command"],
  configLocations: [
    "~/.codex/hooks.json",
    "~/.codex/config.toml",
    "<repo>/.codex/hooks.json",
  ],
  eventNameMap: {
    session_start: "SessionStart",
    user_prompt_submit: "UserPromptSubmit",
    pre_tool_use: "PreToolUse",
    post_tool_use: "PostToolUse",
    permission_request: "PermissionRequest",
    subagent_start: "SubagentStart",
    subagent_stop: "SubagentStop",
    agent_stop: "Stop",
    pre_compact: "PreCompact",
    post_compact: "PostCompact",
  },
};

export const ANTIGRAVITY_VENDOR_CONFIG: VendorConfig = {
  vendor: "antigravity",
  supportedEvents: [
    "pre_tool_use",
    "post_tool_use",
    "agent_stop",
    "pre_invocation",
    "post_invocation",
  ],
  hookTypes: ["command"],
  configLocations: ["<project>/.antigravity/hooks.json"],
  eventNameMap: {
    pre_tool_use: "PreToolUse",
    post_tool_use: "PostToolUse",
    agent_stop: "Stop",
    pre_invocation: "PreInvocation",
    post_invocation: "PostInvocation",
  },
};
