export const NORMALIZED_EVENTS = [
  "session_start",
  "session_end",
  "setup",
  "instructions_loaded",
  "user_prompt_submit",
  "user_prompt_expansion",
  "message_display",
  "pre_tool_use",
  "post_tool_use",
  "post_tool_use_failure",
  "post_tool_batch",
  "permission_request",
  "permission_denied",
  "subagent_start",
  "subagent_stop",
  "task_created",
  "task_completed",
  "agent_stop",
  "stop_failure",
  "error_occurred",
  "pre_invocation",
  "post_invocation",
  "pre_compact",
  "post_compact",
  "notification",
  "config_change",
  "cwd_changed",
  "file_changed",
  "worktree_create",
  "worktree_remove",
  "elicitation",
  "elicitation_result",
  "teammate_idle",
] as const;

export type NormalizedEventName = (typeof NORMALIZED_EVENTS)[number];
